# DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hidiscuss?autoReconnect=true
    hikari:
      username: root
      password: 17181718
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
     # ddl-auto: none
      ddl-auto: create
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 29c5a8f5ca9d173267c4
            client-secret: bdc54f75e0d8c01a641336e5d564e28e15802ec4
