# DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hidiscuss?autoReconnect=true
    hikari:
      username: root
      password: 17181718
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # ddl-auto: none
      ddl-auto: create
    generate-ddl: true

